version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4.18
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/init.js:/scripts/init.js
      - /volume1/docker/mongodb-replicaset2/db:/data/db
      - ./keyfile:/keyfile
    networks:
      - mongo-network
    ports:
      - 27017:27017
    restart: always
    command: mongod --bind_ip_all --replSet rs1

networks:
  mongo-network:
    driver: bridge